### ISSUE TITLE
Add Expire Now button in user listing

### ISSUE THREAD

**Issue by ernilambar** [DrewAPicture/Support-Me#9]
In the user listing, we could add `Expire Now` to expire that account immediately. A kind of kill switch :smile:

**Comment by DrewAPicture** [comment]
I played around with this a little bit, mostly in the realm of destroying the user session, but that's before I moved to doing the expiration on a cron job. We could look at this for 1.1.

**Comment by DrewAPicture** [comment]
At this point, I think it's best to just skip this and go with deleting the user is the same as instantly expiring them. Kinda pointless to expire the user since they'll be deleted shortly after anyway. Thanks for the suggestion!
